config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # delete('/projects/:id', to: 'projects#destroy')

  resource :session, only: [:new, :create, :destroy]

  resources :users, shallow: true do
      resources :projects, only: [:new, :create, :edit, :update, :show, :destroy]
  end

  resources :projects, shallow: true do
      resources :images, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
  end

  # Users#index
  get('/', {to: 'users#index', as: :root})

  post('/contact_me', to: 'users#contact_me')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :project
  mount_uploader :avatar, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :project
  
end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :user
  has_many :images, dependent: :destroy

  has_many :likes, dependent: :destroy
  # has_many :likers, through: :likes, source: :user

  mount_uploader :thumbnail, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord

  has_many :projects, dependent: :destroy

  has_secure_password

  validates :first_name, :last_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email,
    presence: true,
    uniqueness: true,
    format: VALID_EMAIL_REGEX

  def full_name
    "#{first_name} #{last_name}".strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# protect_from_forgery with: :exception
# protect_from_forgery

  private
  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find_by(id: session[:user_id])
      # 👆 OR-EQUAL only assigns to variable if variable is `nil`
      # @current_user = @current_user || User.find(session[:user_id]))
    end
  end
  helper_method :current_user

  def authenticate_user!
    unless user_signed_in?
      flash[:alert] = 'You sign in or sign up first!'
      redirect_to new_session_path
    end
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  # before_action :find_image, :authorize_user!, only: [:destroy]
  before_action :find_image, only: [:destroy]

  def create
    @project = Project.find params[:project_id]
    @image = Image.new image_params
    @image.project = @project

    if @image.save
      redirect_to project_path(@project)
    else
      @images = @project.images.order(created_at: :desc)
      render 'projects/show'
    end
  end

  def destroy
    @image.destroy
    redirect_to project_path(@image.project)
  end

  private
  def image_params
    params.require(:image).permit(:avatar)
  end

  def find_image
    @image ||= Image.find params[:id]
  end

  # def authorize_user!
  #   unless can?(:manage, @image)
  #     flash[:alert] = 'Access Denied!'
  #     redirect_to question_path(@answer.question)
  #   end
  # end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # before_action :authenticate_user!

  def create
    project = Project.find params[:project_id]
    # like = Like.new user: current_user, project: project
    like = Like.new project: project
    like.save

    redirect_to project_path(project), notice: 'Liked'

    # if !can?(:like, project)
    #   redirect_to project, alert: 'can\'t like project'
    # elsif like.save
    #   # redirect_to project_path(project), notice: 'Liked'
    #   redirect_to project, notice: 'Liked'
    # else
    #   redirect_to project, alert: 'Not Liked'
    # end
  end

  def destroy
    like = Like.find params[:id]
    like.destroy
    redirect_to like.project, notice: 'Like removed'

    # if can? :destroy, like
    #   like.destroy
    #   # q = like.question
    #   # redirect_to question_path(q), notice: 'Like removed'
    #   redirect_to like.project, notice: 'Like removed'
    # else
    #   redirect_to like.project, alert: 'can\'t delete like'
    # end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_project, except: [:new, :index, :create]

  def new
    @user = User.find params[:user_id]
    @project = Project.new
  end

  def create
    @user = User.find params[:user_id]
    @project = Project.new project_params
    @project.user = @user

    if @project.save
      redirect_to root_path
    else
      render '/users'
    end
  end

  def show
    @project = Project.find params[:id]
    @image = Image.new
    @images = @project.images
    # @like = @project.likes
  end

  def edit
    # @project = Project.find params[:id]
  end

  def update
    # @project = Project.find params[:id]
    # @project.slug = nil # this will force friendly_id to regenerate slug
    if @project.update project_params
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    #@project = Project.find params[:id]

    @project.destroy
    redirect_to root_path
  end

  private
  def find_project
    @project = Project.find params[:id]
  end

  def project_params
    params.require(:project).permit(
      :title, :description, :thumbnail,
      :project_type, :project_client,
      :thumbnail_title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # skip_before_action :verify_authenticity_token,
  # skip_before_action :verify_authenticity_token, only: :destroy

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'Thank you for signing in!'
      redirect_to root_path
    else
      flash.now[:alert] = 'Wrong email or password!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Signed out!'
    redirect_to root_path
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @user = User.first
    @projects = @user.projects.order(created_at: :asc)
    # render :index
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing in!"
      redirect_to root_path
    else
      render :new
    end
  end

  def contact_me
    @data = contact_me_params
    ContactMailer
      .contact_me_mailer(@data)
      .deliver_now
      # .deliver_later(wait: 10.seconds)

    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end

  def contact_me_params
    params.require(:contact_me).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="https://static.tumblr.com/3e3ebffeb3caceba6c74fbfdaea855d8/y5mzi7v/vwao2arml/tumblr_static_3vyyvcpylm0wok00s0ss4ocko.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Design by Liz</title>

    <!-- Bootstrap core CSS -->
    <link href="../assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <!-- <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous"></script> -->
    <!-- <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script> -->

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="../assets/agency.min.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style="background-color: #212529">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/">
          <img src="/assets/flower.png" width="30" height="30" alt="">
          Liz Balbino</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/#portfolio">Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/#contact">Contact</a>
            </li>
            <li class="nav-item">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger">Hello, <%= current_user.first_name %>!</a>
                </li>
                <!-- <a class="nav-link js-scroll-trigger" href="/session" method = "DELETE">Sign Out</a> -->
                <li class="nav-item">
                  <%= link_to 'Sign Out', session_path, method: :delete, class: "nav-link js-scroll-trigger" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'New Project', new_user_project_path(current_user.id), class: "nav-link js-scroll-trigger" %>
                </li>
              <% else %>
              <!-- <a class="nav-link js-scroll-trigger" href="/session/new">Sign In</a> -->
              <!-- <a class="nav-link js-scroll-trigger" href="/users/new">Sign Up</a> -->
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <%# <div class="container-fluid">%>
    <div class="">
      <% if flash[:notice].present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% elsif flash[:alert].present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

    </div>

    <%= yield %>


    <!-- Bootstrap core JavaScript -->
    <script src="https://blackrockdigital.github.io/startbootstrap-agency/vendor/jquery/jquery.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-agency/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://blackrockdigital.github.io/startbootstrap-agency/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Contact form JavaScript -->
    <!-- <script src="https://blackrockdigital.github.io/startbootstrap-agency/js/jqBootstrapValidation.js"></script> -->
    <!-- <script src="https://blackrockdigital.github.io/startbootstrap-agency/js/contact_me.js"></script> -->

    <!-- Custom scripts for this template -->
    <script src="https://blackrockdigital.github.io/startbootstrap-agency/js/agency.min.js"></script>

  </body>

</html>

app/views/projects/_form.html.erb
<%= simple_form_for [@user, @project] do |f| %>

  <% if @project.errors.present? %>
    <p><%= @project.errors.full_messages.join(', ') %></p>
  <% end %>

  <%= f.input :thumbnail_title %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :project_type %>
  <%= f.input :project_client %>
  <%= f.input :thumbnail %>

  <%= f.submit class: 'btn btn-primary' %>


<% end %>

app/views/projects/edit.html.erb
<div class="" style="margin-top: 100px;
     margin-left: 70px;
     margin-right: 70px">

  <h2>Edit Project</h2>

  <%= render 'form' %>

</div>

app/views/projects/new.html.erb
<div class="" style="margin-top: 100px;
     margin-left: 70px;
     margin-right: 70px">

  <h2>New Project</h2>

  <%= render 'form' %>

</div>

app/views/projects/show.html.erb
<div class="container-project" id="top_project">

  <div class="left">

    <div style="font-size: 50px; font-weight: 700; margin-bottom:20px;
      font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">
      <%= @project.title %>
    </div>

    <div style="margin-bottom:50px; margin-left:auto; margin-right:auto; text-align:center; width:70%; font-size: 16px; font-family: 'Roboto Slab','Helvetica Neue',Helvetica,Arial,sans-serif">
      <%= @project.description %><br>
    </div>

    <div class="">
      <% @images.each do |image| %>
        <img src="<%= image.avatar %>"/>
        <p></p>
        <% if user_signed_in? %>
          <%= link_to 'Delete Image', image_path(image), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        <p></p>
      <% end %>
    </div>

    <div class="">
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="/#portfolio" style="font-weight: 400;
        font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">Close Project</a>
    </div>
    <br>
    <div class="">
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#top_project" style="font-weight: 400;
        font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">Top page</a>
    </div>

  </div>

  <div class="sidebar">
    <div class="right">
      <div class="" style="text-align: center">
        <img class="rounded-circle " src="../assets/Liz.jpg" style="width: 60px; height: 60px; margin-bottom: 10px;"/>
      </div>
      <div class="" style="font-size: 20px; text-align: center; font-weight: 400;
      font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">
        LIZ BALBINO<p></p>
      </div>
    </div>
    <hr>

    <div class="right">
      <div style="font-size: 15px; font-weight: 600;
      font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">
        Client:
      </div>

      <div style="font-size:15px; font-family: 'Roboto Slab','Helvetica Neue',Helvetica,Arial,sans-serif;">
        <%= @project.project_client %>
        <p></p>
      </div>

      <div style="font-size: 15px; font-weight: 600;
      font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">
        Categories:
      </div>

      <div style="font-size:15px; font-family: 'Roboto Slab','Helvetica Neue',Helvetica,Arial,sans-serif;">
        <%= @project.project_type %>
        <p></p>
      </div>

      <div style="font-size: 12px; font-weight: 400;
      font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">
        Published
        <%= time_ago_in_words(@project.created_at) %>
        ago
      </div>
    </div>
    <hr>

    <div class="right">
      <%= link_to fa_icon('thumbs-o-up 2x'), project_likes_path(@project), method: :post %>
      <%= pluralize(@project.likes.count, 'like') %>
    </div>
    <hr>

    <% if user_signed_in? %>
      <div >
        <%= link_to 'Edit Project', edit_project_path(@project) %>
      </div>

      <div class="">
        <%= link_to 'Delete Project', project_path(@project), method: :delete,
            data: { confirm: 'Are you sure?' } %>
        <a href="/#portfolio"></a>
      </div>

      <div class="">
        <%= simple_form_for [@project, @image] do |f| %>
        <%= f.input :avatar %>
        <%= f.submit 'Add image', class: 'btn btn-primary' %>
        <% end %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<!-- Header -->
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">Welcome to my Portfolio!</div>
      <div class="intro-heading text-uppercase">It's Nice To Meet You</div>
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#services" style="font-weight: 400;
      font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">More about me</a>
    </div>
  </div>
</header>

<!-- Services -->
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase" style="font-weight: 600;
        font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif">Services</h2>
        <!-- <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3> -->
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <!-- <i class="fa fa-circle fa-stack-2x text-primary"></i> <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i> -->
        </span>
        <h4 class="service-heading" style="font-weight: 400;
        font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">Graphic Design</h4>
        <p class="text-muted" style="font-weight:300; font-family: 'Roboto Slab','Helvetica Neue',Helvetica,Arial,sans-serif;">
          Graphic design is the process of visual communication and problem-solving using typography, photography, illustration and many others.
        </div>
        <div class="col-md-4">
          <img style="border-radius: 150px; height: 250px; margin-bottom: 30px" src="./Liz.jpeg">
          <p class="text-muted" style="font-weight:300; font-family: 'Roboto Slab','Helvetica Neue',Helvetica,Arial,sans-serif;">
            <%= @user.profile_title %>
            <br>
            <%= @user.profile_company %>
            <br>
            <%= @user.address %></p>

        </div>
        <div class="col-md-4">
          <span class="fa-stack fa-4x">
            <!-- <i class="fa fa-circle fa-stack-2x text-primary"></i> <i class="fa fa-lock fa-stack-1x fa-inverse"></i> -->
          </span>
          <h4 class="service-heading" style="font-weight: 400;
        font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">Web Design</h4>
          <p class="text-muted" style="font-weight:300; font-family: 'Roboto Slab','Helvetica Neue',Helvetica,Arial,sans-serif;">
            Web design encompasses many different skills and disciplines in the production and maintenance of websites.
          </div>
        </div>
      </div>
    </section>

    <!-- Portfolio Grid -->
    <section class="bg-light" id="portfolio">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase" style="font-weight: 600;
          font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">Portfolio</h2>
            <h3 class="section-subheading text-muted">Here's a little bit of the work I do and love...</h3>
          </div>
        </div>
        <div class="row">
          <% @projects.each do |project| %>
            <div class="col-md-4 col-sm-6 portfolio-item" style="font-weight: 700;
        font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;" id="project-<%= project.id %>">
              <a class="portfolio-link" href="/projects/<%= project.id %>">
                <!-- <a class="portfolio-link" data-toggle="modal" href="/projects/show/<%= project.id %>"> -->
                <!-- <a class="portfolio-link" href="projects/show"> -->
                <div class="portfolio-hover">
                  <div class="portfolio-hover-content">
                    <i class="fa fa-plus fa-3x"></i>
                    <!-- <i class="fa fa-plus-square"></i> -->
                  </div>
                </div>
                <img class="img-fluid" src="<%= project.thumbnail.url(:medium)%>" alt="<%= project.title%>">
              </a>
              <div class="portfolio-caption">
                <a class="portfolio-link" href="/projects/<%= project.id %>">
                  <h4><%= project.thumbnail_title%></h4>
                  <!-- <p class="text-muted"><%= project.project_client%></p> -->
                </a>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </section>

    <!-- About -->
    <section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase" style="font-weight: 600;
        font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">About</h2>
            <h3 class="section-subheading text-muted">Here's a little bit of me and my jorney as a Graphic Designer...</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <ul class="timeline">
              <li>
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="./about1.jpg" alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading" style="font-weight: 400;
              font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">
                    <h4>July 2011</h4>
                    <h4 class="subheading">The Amatteur Designer</h4>
                  </div>
                  <div class="timeline-body">
                    <p class="text-muted" style="font-weight:300; font-family: 'Roboto Slab','Helvetica Neue',Helvetica,Arial,sans-serif;">It all started way back then, in a social media were everyone wanted "banners" to put in their profile, I've never liked depending
                      on people to do things for me so started learning by myself how to use Photoshop and Illustrator, I was always doing those banners not only for me but also for other people online that like mine and asked me to do it for them.</p>
                  </div>
                </div>
              </li>
              <li class="timeline-inverted">
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="./about2.jpg" alt="">
                  <!-- <img class="rounded-circle img-fluid" src="<%= @user.image %>" alt=""> -->
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading" style="font-weight: 400;
              font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">
                    <h4>February 2016</h4>
                    <h4 class="subheading">First Time in College</h4>
                  </div>
                  <div class="timeline-body" style="font-weight:300; font-family: 'Roboto Slab','Helvetica Neue',Helvetica,Arial,sans-serif;">
                    <p class="text-muted">During my childhood I've always wanted to go to medical school and become a plastic surgeon, but when I moved from my hometown to a bigger city, I saw the world from a different perspective and found out that Graphic Design was
                      really a thing and I didn't have to be a doctor to be successful in life.That was when I started my first College with a major in Graphic Design.</p>
                  </div>
                </div>
              </li>
              <li>
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="./about3.jpg" alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading" style="font-weight: 400;
              font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">
                    <h4>April 2017</h4>
                    <h4 class="subheading">Designing in Vancouver</h4>
                  </div>
                  <div class="timeline-body" style="font-weight:300; font-family: 'Roboto Slab','Helvetica Neue',Helvetica,Arial,sans-serif;">
                    <p class="text-muted">Things in the bigger city were not going as well as planned, so my parents started doing some research and fell in love with Vancouver, when they came to me with the idea I didn't think twice about saying YES. And now here I am
                      living my dream as Graphic Designer student in this beautiful and lovely city.</p>
                  </div>
                </div>
              </li>
              <li class="timeline-inverted">
                <div class="timeline-image text-uppercase" style="font-weight: 800;
            font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">
                  <h4>Be Part
                    <br>Of My
                    <br>Story!</h4>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <!-- Contact -->
    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase" style="font-weight: 600;
        font-family: Montserrat, 'Helvetica Neue', Helvetica, Arial, sans-serif;">Contact Me</h2>
            <h3 class="section-subheading text-muted">Let me know what you are thinking!</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <form action="/contact_me" method="post" id="contactForm" name="sentMessage" novalidate="novalidate">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <input class="form-control" name="contact_me[name]" id="name" type="text" placeholder=" Your Name *" required="required" data-validation-required-message="Please enter your name.">
                    <p class="help-block text-danger"></p>
                  </div>
                  <div class="form-group">
                    <input class="form-control" name="contact_me[email]" id="email" type="email" placeholder="Your Email *" required="required" data-validation-required-message="Please enter your email address.">
                    <p class="help-block text-danger"></p>
                  </div>
                  <div class="form-group">
                    <input class="form-control" name="contact_me[phone]" id="phone" type="tel" placeholder="Your Phone *" required="required" data-validation-required-message="Please enter your phone number.">
                    <p class="help-block text-danger"></p>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <textarea class="form-control" name="contact_me[message]" id="message" placeholder="Your Message *" required="required" data-validation-required-message="Please enter a message."></textarea>
                    <p class="help-block text-danger"></p>
                  </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-lg-12 text-center">
                  <div id="success"></div>
                  <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">
                    Send Message
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer>

      <div class="container">
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="<%= @user.url_facebook %>">
                  <i class="fa fa-facebook-square"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="<%= @user.url_instagram %>">
                  <i class="fa fa-instagram"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="<%= @user.url_linkedin %>">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

app/views/users/new.html.erb
<div class="" style="margin-top: 150px">
  <h1>Sign Up</h1>

  <%= simple_form_for @user do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :password, as: :string %>
    <%= f.input :password_confirmation %>

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>